DROP TABLE IF EXISTS film_genre CASCADE;
DROP TABLE IF EXISTS genres CASCADE;
DROP TABLE IF EXISTS likes CASCADE;
DROP TABLE IF EXISTS friends CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS films CASCADE;
DROP TABLE IF EXISTS mpa CASCADE;

CREATE TABLE IF NOT EXISTS users(
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    login VARCHAR NOT NULL,
    name VARCHAR,
    email VARCHAR NOT NULL,
    birthday VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS friends(
    id_user bigint REFERENCES users(id) NOT NULL ON DELETE CASCADE,
    id_friend bigint REFERENCES users(id) NOT NULL ON DELETE CASCADE,
    CONSTRAINT "friends_pk" PRIMARY KEY (user_id, friend_id)
    );

CREATE TABLE IF NOT EXISTS films(
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    name VARCHAR NOT NULL,
    description VARCHAR,
    releaseDate VARCHAR NOT NULL,
    duration INT NOT NULL,
    mpa_id INTEGER REFERENCES mpa(id_mpa) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS mpa(
    id_mpa INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    mpa_name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS genres(
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    genre_name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS likes(
    film_id bigint NOT NULL REFERENCES films(id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT "likes_pk" PRIMARY KEY (film_id, user_id)
)

CREATE TABLE IF NOT EXISTS film_genre(
    film_id bigint NOT NULL REFERENCES films(id) ON DELETE CASCADE,
    genre_id INTEGER NOT NULL REFERENCES genres(id) ON DELETE CASCADE,
    CONSTRAINT "film_genre_pk" PRIMARY KEY (film_id, genre_id)
)
